#!/usr/bin/env python3
"""Generate the reference tables under docs/ directly from the data structures in
``abq2ccx.py``, so the documentation can never drift from the code.

Run after changing any of the keyword/element/output tables:

    python docs/generate_reference.py

It (re)writes:  docs/keyword-reference.md, docs/element-reference.md,
docs/output-reference.md
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)
import abq2ccx as A  # noqa: E402

AUTOGEN = "<!-- AUTO-GENERATED by docs/generate_reference.py — do not edit by hand. -->\n"

# Keywords handled by a dedicated translator (translate_one dispatch + build_geometry).
TRANSLATED = {
    "*NODE / *ELEMENT / *NSET / *ELSET": "parsed into the geometry registry and re-emitted "
        "canonically (sets resolved, `GEN`→`GENERATE`, gappy ranges pruned).",
    "*NGEN / *NFILL / *NCOPY / *ELGEN / *ELCOPY": "expanded into explicit `*NODE`/`*ELEMENT` "
        "(CalculiX has no mesh-generation cards).",
    "*PART / *INSTANCE / *ASSEMBLY": "flattened into one global numbering (instance transform "
        "applied, references resolved, names kept ≤20 chars).",
    "*ELASTIC": "`TYPE` token translated (`ORTHOTROPIC`→`ORTHO`, `ANISOTROPIC`→`ANISO`); data "
        "passed through (constant order identical).",
    "*ORIENTATION": "`DEFINITION` dropped; `SPHERICAL`→`RECTANGULAR` (warned); rotation line kept.",
    "*DISTRIBUTION": "passed through with a warning (ccx supports it on `*SOLID SECTION` only).",
    "*SOLID SECTION": "keeps `ELSET`/`MATERIAL`/`ORIENTATION`; other params dropped.",
    "*SHELL SECTION": "thickness only (integration-point count dropped); composite plies → one "
        "synthesized `*ORIENTATION` per ply angle (S6/S8R only).",
    "*SHELL GENERAL SECTION": "→ `*SHELL SECTION` (thickness+material form); ABD/stiffness form "
        "flagged as unsupported.",
    "*BEAM SECTION": "keeps the supported params; `SECTION=CIRC` radius-vs-axes mismatch flagged.",
    "*STEP": "`NAME` dropped; `NLGEOM` kept on the step; `PERTURBATION` kept only for "
        "`*FREQUENCY`/`*BUCKLE`; `*END STEP` ensured.",
    "*BOUNDARY": "named types (`ENCASTRE`/`PINNED`/`*SYMM`) expanded to DOFs; `TYPE=` stripped.",
    "*DLOAD": "passed through (`Px` faces match Abaqus); bare `P` on solids flagged.",
    "*DSLOAD": "surface pressure → `*DLOAD` with `Px` face labels.",
    "*TIE": "Abaqus-only params (`TYPE=`) stripped; `ADJUST`/`POSITION TOLERANCE` kept.",
    "*MPC": "`TIE` → per-DOF `*EQUATION`; `PLANE`/`STRAIGHT` kept; others commented.",
    "*KINEMATIC COUPLING": "→ `*RIGID BODY` (all 6 DOFs).",
    "*CREEP": "Abaqus `LAW=STRAIN/TIME` → ccx Norton (default); other laws → `LAW=USER`.",
    "*AMPLITUDE": "keeps `NAME`/`TIME`; non-tabular `DEFINITION` flagged. (`*AMP` alias accepted.)",
    "*RESTART": "keeps `WRITE`/`READ`/`FREQUENCY`/`STEP`; other params dropped.",
    "*SURFACE": "passed through; `ANALYTICAL RIGID` commented; `SPOS`/`SNEG` flagged.",
    "*OUTPUT / *NODE OUTPUT / *ELEMENT OUTPUT": "→ `*NODE FILE`/`*EL FILE`; `*OUTPUT` wrapper "
        "dropped.",
    "*NODE FILE / *EL FILE / *NODE PRINT / *EL PRINT": "`POSITION=` stripped, `FREQ`→`FREQUENCY`, "
        "`FREQUENCY=0` dropped, variables mapped/filtered.",
}


def md_table(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "| " + " | ".join("---" for _ in headers) + " |"]
    for r in rows:
        out.append("| " + " | ".join(str(c) for c in r) + " |")
    return "\n".join(out)


def element_category(t):
    checks = [
        (("SPRING", "DASHPOT", "GAPUNI", "GAPCYL", "GAPSPHER", "MASS", "DCOUP", "ROTARYI"), "discrete"),
        (("COH",), "cohesive"),
        (("CONN",), "connector"),
        (("R3D", "RB2", "RB3", "RAX"), "rigid"),
        (("DC3D", "DC1D"), "heat-transfer continuum"),
        (("C3D",), "3D continuum"),
        (("F3D",), "3D fluid (CFD)"),
        (("M3D",), "membrane"),
        (("CPS",), "plane stress"),
        (("CPEG",), "generalized plane strain"),
        (("CPE",), "plane strain"),
        (("CGAX",), "generalized axisymmetric"),
        (("CAX",), "axisymmetric"),
        (("STRI", "SC", "DS", "US", "S"), "shell"),
        (("PIPE", "T2D", "T3D", "B"), "beam / truss"),
    ]
    if t == "D":
        return "fluid/network"
    for prefixes, name in checks:
        if t.startswith(prefixes):
            return name
    return "other"


def element_status(t):
    if t in A.ELEMENT_TYPE_MAP:
        return f"→ `{A.ELEMENT_TYPE_MAP[t]}` (substituted)"
    if t in A.CCX_ELEMENTS:
        return "direct"
    if t.endswith("H") and t[:-1] in A.CCX_ELEMENTS:
        return f"→ `{t[:-1]}` (hybrid)"
    if t.startswith(("R3D", "RB2", "RB3", "RAX")):
        return "flagged → model as `*RIGID BODY`"
    if t.startswith(A.UNSUPPORTED_ELEM_PREFIXES):
        return "flagged — no ccx equivalent"
    return "passed through (verify)"


def gen_elements():
    cats = {}
    for t in sorted(A.ELEMENT_NNODES):
        cats.setdefault(element_category(t), []).append(t)
    parts = [AUTOGEN, "# Element reference\n",
             "Every Abaqus element type the converter recognises, its node count, and how it is "
             "emitted for CalculiX. **Substitutions preserve the node count** so connectivity stays "
             "valid. Solid/shell node *ordering* is identical between the two codes, so connectivity "
             "is passed through unchanged.\n",
             f"Direct CalculiX types: **{len(A.CCX_ELEMENTS)}**. Total recognised: "
             f"**{len(A.ELEMENT_NNODES)}**.\n"]
    for cat in sorted(cats):
        rows = [(f"`{t}`", A.ELEMENT_NNODES[t], element_status(t)) for t in cats[cat]]
        parts.append(f"## {cat}\n")
        parts.append(md_table(["Abaqus type", "Nodes", "CalculiX"], rows) + "\n")
    return "\n".join(parts)


def gen_keywords():
    handled = {"NODE", "ELEMENT", "NSET", "ELSET", "NGEN", "NFILL", "NCOPY", "NMAP", "ELGEN",
               "ELCOPY", "ELASTIC", "ORIENTATION", "DISTRIBUTION", "SOLID SECTION", "SHELL SECTION",
               "BEAM SECTION", "STEP", "END STEP", "BOUNDARY", "DLOAD", "DSLOAD", "TIE", "MPC",
               "CREEP", "AMPLITUDE", "RESTART", "SURFACE", "OUTPUT", "NODE OUTPUT", "ELEMENT OUTPUT",
               "NODE FILE", "EL FILE", "NODE PRINT", "EL PRINT"}
    supported = sorted(k for k in A.CCX_KEYWORDS
                       if k not in handled and k not in A.PASS_WITH_NOTE and k not in A.SEMANTIC_TRAP)
    parts = [AUTOGEN, "# Keyword reference\n",
             "How each Abaqus keyword is handled. The converter knows the complete CalculiX 2.22 "
             f"keyword set (**{len(A.CCX_KEYWORDS)}** cards). Anything in that set is emitted as-is; "
             "anything outside it without a translator is commented out with guidance — never "
             "silently dropped.\n",
             "## Translated / converted to an equivalent\n",
             md_table(["Abaqus keyword", "Handling"],
                      [(f"`{k}`", v) for k, v in TRANSLATED.items()]) + "\n",
             "## Supported — emitted unchanged\n",
             "CalculiX accepts these as-is (verified against the ccx 2.22 manual):\n",
             ", ".join(f"`*{k}`" for k in supported) + "\n",
             "## Passed through with a heads-up\n",
             md_table(["Keyword", "Note"], [(f"`*{k}`", v) for k, v in A.PASS_WITH_NOTE.items()]) + "\n",
             "## Same name, different meaning (warned)\n",
             md_table(["Keyword", "Warning"], [(f"`*{k}`", v) for k, v in A.SEMANTIC_TRAP.items()]) + "\n",
             "## Dropped — organisational, no ccx meaning\n",
             "Silently dropped (with a note): "
             + ", ".join(f"`*{k}`" for k in sorted(A.DROP_KEYWORDS)) + ".\n",
             "Dropped with a warning (can change the model):\n",
             md_table(["Keyword", "Warning"],
                      [(f"`*{k}`", v) for k, v in A.DROP_WARN_KEYWORDS.items()]) + "\n",
             "## No CalculiX equivalent — commented out with guidance\n",
             "Any keyword not in the CalculiX set and without a translator is emitted as `**` "
             "comments plus a warning. These have tailored guidance:\n",
             md_table(["Keyword", "Guidance"],
                      [(f"`*{k}`", v) for k, v in A.SPECIAL_UNSUPPORTED.items()]) + "\n"]
    return "\n".join(parts)


def gen_output():
    parts = [AUTOGEN, "# Output-variable reference\n",
             "How Abaqus field/history output identifiers map to CalculiX `*NODE FILE` / "
             "`*EL FILE` / `*NODE PRINT` / `*EL PRINT` variables.\n",
             "## Renamed / folded onto a CalculiX identifier\n",
             md_table(["Abaqus", "CalculiX"],
                      [(f"`{a}`", f"`{c}`") for a, c in sorted(A.ABQ_MAP_VARS.items())]) + "\n",
             "## Dropped — no CalculiX equivalent (derive in post-processing)\n",
             ", ".join(f"`{v}`" for v in sorted(A.ABQ_DROP_VARS)) + "\n",
             "## Valid only on `*EL PRINT` / `*NODE PRINT` (.dat)\n",
             "Dropped from `*EL FILE`/`*NODE FILE` (.frd): "
             + ", ".join(f"`{v}`" for v in sorted(A.EL_PRINT_ONLY_VARS)) + ".\n"]
    return "\n".join(parts)


def main():
    for name, text in [("keyword-reference.md", gen_keywords()),
                       ("element-reference.md", gen_elements()),
                       ("output-reference.md", gen_output())]:
        with open(os.path.join(HERE, name), "w") as fh:
            fh.write(text.rstrip() + "\n")
        print("wrote", os.path.join("docs", name))


if __name__ == "__main__":
    main()
